# Reload config with <prefix> + r
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded!"

# Easier split navigation (Alt + arrow keys)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
set -g mouse on                   # Enable mouse support

# Core settings
set -g history-limit 10000
set -g base-index 1              # Windows start at 1
setw -g pane-base-index 1        # Panes start at 1
set -sg escape-time 0            # no delay on escape
setw -g mode-keys vi             # Use vi keys in copy mode

##### PLUGINS #####
# TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Catppuccin (Use this if using TPM)
#set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/catppuccin-tmux'

# Catppuccin settings
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
# Auto-save and restore tmux sessions
set -g @resurrect-strategy-nvim 'session'

# Load TPM plugins (MUST be last)
run '~/.tmux/plugins/tpm/tpm'

